short_name = "OIP"
name = "Open Industry Project"
major = 4
minor = 7
patch = 0
status = "stable"
module_config = ""
website = "https://github.com/Automation-Standard/Open-Industry-Project"
docs = "4.7"
