short_name = "OIP"
name = "Open Industry Project"
major = 4
minor = 3
patch = 0
status = "beta"
module_config = ""
year = 2024
website = "https://github.com/Automation-Standard/Open-Industry-Project"
docs = "4.3"
